@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
### Signup User

POST {{host}}/auth/signup
Content-Type: application/json

{
    "password": "123456",
    "email": "ehmusman4@gmail.com"
}

### Signin

POST {{host}}/auth/signin
Content-Type: application/json

{
    "password": "123456",
    "email": "ehmusman4@gmail.com"
}

### Get Self Profile

GET {{host}}/auth/whoAmI

### Signout

POST {{host}}/auth/signout


### Find a user with ID

GET {{host}}/auth/7

### Find all users with email

GET {{host}}/auth?email=ehmusman1@gmail.com


### List All Users
GET {{host}}/auth/users


### Delete User by ID

DELETE {{host}}/auth/3

### Update User

PATCH {{host}}/auth/8
Content-Type: application/json

{
    "email": "ehmusman1@gmail.com"
}
